// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/tsscomm/v1/tsscomm.proto

package tsscommv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DirectLink_Send_FullMethodName = "/xlabs.tss.comm.DirectLink/Send"
)

// DirectLinkClient is the client API for DirectLink service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DirectLink is used for TSS communications between guardians.
// Since TSS requires reliable broadcast logic
type DirectLinkClient interface {
	// Send uses a stream since the clients of this RPC will invoke it multiple times throughout the life of the server.
	Send(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PropagatedMessage, emptypb.Empty], error)
}

type directLinkClient struct {
	cc grpc.ClientConnInterface
}

func NewDirectLinkClient(cc grpc.ClientConnInterface) DirectLinkClient {
	return &directLinkClient{cc}
}

func (c *directLinkClient) Send(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PropagatedMessage, emptypb.Empty], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DirectLink_ServiceDesc.Streams[0], DirectLink_Send_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PropagatedMessage, emptypb.Empty]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DirectLink_SendClient = grpc.ClientStreamingClient[PropagatedMessage, emptypb.Empty]

// DirectLinkServer is the server API for DirectLink service.
// All implementations must embed UnimplementedDirectLinkServer
// for forward compatibility.
//
// DirectLink is used for TSS communications between guardians.
// Since TSS requires reliable broadcast logic
type DirectLinkServer interface {
	// Send uses a stream since the clients of this RPC will invoke it multiple times throughout the life of the server.
	Send(grpc.ClientStreamingServer[PropagatedMessage, emptypb.Empty]) error
	mustEmbedUnimplementedDirectLinkServer()
}

// UnimplementedDirectLinkServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDirectLinkServer struct{}

func (UnimplementedDirectLinkServer) Send(grpc.ClientStreamingServer[PropagatedMessage, emptypb.Empty]) error {
	return status.Errorf(codes.Unimplemented, "method Send not implemented")
}
func (UnimplementedDirectLinkServer) mustEmbedUnimplementedDirectLinkServer() {}
func (UnimplementedDirectLinkServer) testEmbeddedByValue()                    {}

// UnsafeDirectLinkServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DirectLinkServer will
// result in compilation errors.
type UnsafeDirectLinkServer interface {
	mustEmbedUnimplementedDirectLinkServer()
}

func RegisterDirectLinkServer(s grpc.ServiceRegistrar, srv DirectLinkServer) {
	// If the following call pancis, it indicates UnimplementedDirectLinkServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DirectLink_ServiceDesc, srv)
}

func _DirectLink_Send_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DirectLinkServer).Send(&grpc.GenericServerStream[PropagatedMessage, emptypb.Empty]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DirectLink_SendServer = grpc.ClientStreamingServer[PropagatedMessage, emptypb.Empty]

// DirectLink_ServiceDesc is the grpc.ServiceDesc for DirectLink service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DirectLink_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xlabs.tss.comm.DirectLink",
	HandlerType: (*DirectLinkServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Send",
			Handler:       _DirectLink_Send_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/tsscomm/v1/tsscomm.proto",
}
