// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/tsscomm/v1/tsscomm.proto

package tsscommv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// copyOfTssLib proto.
type PartyId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartyId) Reset() {
	*x = PartyId{}
	mi := &file_proto_tsscomm_v1_tsscomm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartyId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartyId) ProtoMessage() {}

func (x *PartyId) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tsscomm_v1_tsscomm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartyId.ProtoReflect.Descriptor instead.
func (*PartyId) Descriptor() ([]byte, []int) {
	return file_proto_tsscomm_v1_tsscomm_proto_rawDescGZIP(), []int{0}
}

func (x *PartyId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type TssContent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Payload         []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	MsgSerialNumber uint64                 `protobuf:"varint,2,opt,name=msg_serial_number,json=msgSerialNumber,proto3" json:"msg_serial_number,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TssContent) Reset() {
	*x = TssContent{}
	mi := &file_proto_tsscomm_v1_tsscomm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TssContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TssContent) ProtoMessage() {}

func (x *TssContent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tsscomm_v1_tsscomm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TssContent.ProtoReflect.Descriptor instead.
func (*TssContent) Descriptor() ([]byte, []int) {
	return file_proto_tsscomm_v1_tsscomm_proto_rawDescGZIP(), []int{1}
}

func (x *TssContent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TssContent) GetMsgSerialNumber() uint64 {
	if x != nil {
		return x.MsgSerialNumber
	}
	return 0
}

// SignedMessage is the content of a broadcast message. It may be echoed and as a result requires a signature.
type SignedMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Although we don’t anticipate more senders than 255 (which is equivalent to 1 byte),
	// the uint32 data type is highly optimized in protobuf for sending smaller
	// numbers (refer to https://protobuf.dev/programming-guides/encoding/#simple).
	Sender    uint32 `protobuf:"varint,1,opt,name=sender,proto3" json:"sender,omitempty"` // pointer to specific PartyID
	Signature []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	// Types that are valid to be assigned to Content:
	//
	//	*SignedMessage_TssContent
	//	*SignedMessage_HashEcho
	Content       isSignedMessage_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedMessage) Reset() {
	*x = SignedMessage{}
	mi := &file_proto_tsscomm_v1_tsscomm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedMessage) ProtoMessage() {}

func (x *SignedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tsscomm_v1_tsscomm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedMessage.ProtoReflect.Descriptor instead.
func (*SignedMessage) Descriptor() ([]byte, []int) {
	return file_proto_tsscomm_v1_tsscomm_proto_rawDescGZIP(), []int{2}
}

func (x *SignedMessage) GetSender() uint32 {
	if x != nil {
		return x.Sender
	}
	return 0
}

func (x *SignedMessage) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *SignedMessage) GetContent() isSignedMessage_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *SignedMessage) GetTssContent() *TssContent {
	if x != nil {
		if x, ok := x.Content.(*SignedMessage_TssContent); ok {
			return x.TssContent
		}
	}
	return nil
}

func (x *SignedMessage) GetHashEcho() *HashEcho {
	if x != nil {
		if x, ok := x.Content.(*SignedMessage_HashEcho); ok {
			return x.HashEcho
		}
	}
	return nil
}

type isSignedMessage_Content interface {
	isSignedMessage_Content()
}

type SignedMessage_TssContent struct {
	TssContent *TssContent `protobuf:"bytes,3,opt,name=tss_content,json=tssContent,proto3,oneof"`
}

type SignedMessage_HashEcho struct {
	HashEcho *HashEcho `protobuf:"bytes,6,opt,name=hashEcho,proto3,oneof"`
}

func (*SignedMessage_TssContent) isSignedMessage_Content() {}

func (*SignedMessage_HashEcho) isSignedMessage_Content() {}

type HashEcho struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	SessionUuid           []byte                 `protobuf:"bytes,1,opt,name=sessionUuid,proto3" json:"sessionUuid,omitempty"`                     // should be the relevant uuid. without it, we cant match this echo with the tssContent that we receive a hash of.
	OriginalContentDigest []byte                 `protobuf:"bytes,2,opt,name=originalContentDigest,proto3" json:"originalContentDigest,omitempty"` // should be a hash of what the original sender signed.
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *HashEcho) Reset() {
	*x = HashEcho{}
	mi := &file_proto_tsscomm_v1_tsscomm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HashEcho) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashEcho) ProtoMessage() {}

func (x *HashEcho) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tsscomm_v1_tsscomm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashEcho.ProtoReflect.Descriptor instead.
func (*HashEcho) Descriptor() ([]byte, []int) {
	return file_proto_tsscomm_v1_tsscomm_proto_rawDescGZIP(), []int{3}
}

func (x *HashEcho) GetSessionUuid() []byte {
	if x != nil {
		return x.SessionUuid
	}
	return nil
}

func (x *HashEcho) GetOriginalContentDigest() []byte {
	if x != nil {
		return x.OriginalContentDigest
	}
	return nil
}

// Echo is a message explicitly used by the Reliable Broadcast protocol.
type Echo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *SignedMessage         `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Echo) Reset() {
	*x = Echo{}
	mi := &file_proto_tsscomm_v1_tsscomm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Echo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Echo) ProtoMessage() {}

func (x *Echo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tsscomm_v1_tsscomm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Echo.ProtoReflect.Descriptor instead.
func (*Echo) Descriptor() ([]byte, []int) {
	return file_proto_tsscomm_v1_tsscomm_proto_rawDescGZIP(), []int{4}
}

func (x *Echo) GetMessage() *SignedMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

type Unicast struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Content:
	//
	//	*Unicast_Tss
	Content       isUnicast_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Unicast) Reset() {
	*x = Unicast{}
	mi := &file_proto_tsscomm_v1_tsscomm_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Unicast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Unicast) ProtoMessage() {}

func (x *Unicast) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tsscomm_v1_tsscomm_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Unicast.ProtoReflect.Descriptor instead.
func (*Unicast) Descriptor() ([]byte, []int) {
	return file_proto_tsscomm_v1_tsscomm_proto_rawDescGZIP(), []int{5}
}

func (x *Unicast) GetContent() isUnicast_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Unicast) GetTss() *TssContent {
	if x != nil {
		if x, ok := x.Content.(*Unicast_Tss); ok {
			return x.Tss
		}
	}
	return nil
}

type isUnicast_Content interface {
	isUnicast_Content()
}

type Unicast_Tss struct {
	Tss *TssContent `protobuf:"bytes,1,opt,name=tss,proto3,oneof"`
}

func (*Unicast_Tss) isUnicast_Content() {}

// PropagatedMessage is a message that is sent across the network,
// either to a specific recipient or all nodes (using reliable broadcast).
type PropagatedMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*PropagatedMessage_Unicast
	//	*PropagatedMessage_Echo
	Message       isPropagatedMessage_Message `protobuf_oneof:"Message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PropagatedMessage) Reset() {
	*x = PropagatedMessage{}
	mi := &file_proto_tsscomm_v1_tsscomm_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PropagatedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropagatedMessage) ProtoMessage() {}

func (x *PropagatedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tsscomm_v1_tsscomm_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropagatedMessage.ProtoReflect.Descriptor instead.
func (*PropagatedMessage) Descriptor() ([]byte, []int) {
	return file_proto_tsscomm_v1_tsscomm_proto_rawDescGZIP(), []int{6}
}

func (x *PropagatedMessage) GetMessage() isPropagatedMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *PropagatedMessage) GetUnicast() *Unicast {
	if x != nil {
		if x, ok := x.Message.(*PropagatedMessage_Unicast); ok {
			return x.Unicast
		}
	}
	return nil
}

func (x *PropagatedMessage) GetEcho() *Echo {
	if x != nil {
		if x, ok := x.Message.(*PropagatedMessage_Echo); ok {
			return x.Echo
		}
	}
	return nil
}

type isPropagatedMessage_Message interface {
	isPropagatedMessage_Message()
}

type PropagatedMessage_Unicast struct {
	Unicast *Unicast `protobuf:"bytes,1,opt,name=Unicast,proto3,oneof"`
}

type PropagatedMessage_Echo struct {
	Echo *Echo `protobuf:"bytes,2,opt,name=Echo,proto3,oneof"`
}

func (*PropagatedMessage_Unicast) isPropagatedMessage_Message() {}

func (*PropagatedMessage_Echo) isPropagatedMessage_Message() {}

var File_proto_tsscomm_v1_tsscomm_proto protoreflect.FileDescriptor

const file_proto_tsscomm_v1_tsscomm_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/tsscomm/v1/tsscomm.proto\x12\x0exlabs.tss.comm\x1a\x1bgoogle/protobuf/empty.proto\"\x19\n" +
	"\aPartyId\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"R\n" +
	"\n" +
	"TssContent\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12*\n" +
	"\x11msg_serial_number\x18\x02 \x01(\x04R\x0fmsgSerialNumber\"\xc7\x01\n" +
	"\rSignedMessage\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\rR\x06sender\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\x12=\n" +
	"\vtss_content\x18\x03 \x01(\v2\x1a.xlabs.tss.comm.TssContentH\x00R\n" +
	"tssContent\x126\n" +
	"\bhashEcho\x18\x06 \x01(\v2\x18.xlabs.tss.comm.HashEchoH\x00R\bhashEchoB\t\n" +
	"\acontent\"b\n" +
	"\bHashEcho\x12 \n" +
	"\vsessionUuid\x18\x01 \x01(\fR\vsessionUuid\x124\n" +
	"\x15originalContentDigest\x18\x02 \x01(\fR\x15originalContentDigest\"?\n" +
	"\x04Echo\x127\n" +
	"\amessage\x18\x01 \x01(\v2\x1d.xlabs.tss.comm.SignedMessageR\amessage\"D\n" +
	"\aUnicast\x12.\n" +
	"\x03tss\x18\x01 \x01(\v2\x1a.xlabs.tss.comm.TssContentH\x00R\x03tssB\t\n" +
	"\acontent\"\x7f\n" +
	"\x11PropagatedMessage\x123\n" +
	"\aUnicast\x18\x01 \x01(\v2\x17.xlabs.tss.comm.UnicastH\x00R\aUnicast\x12*\n" +
	"\x04Echo\x18\x02 \x01(\v2\x14.xlabs.tss.comm.EchoH\x00R\x04EchoB\t\n" +
	"\aMessage2Q\n" +
	"\n" +
	"DirectLink\x12C\n" +
	"\x04Send\x12!.xlabs.tss.comm.PropagatedMessage\x1a\x16.google.protobuf.Empty(\x01B)Z'tss/internal/proto/tsscomm/v1;tsscommv1b\x06proto3"

var (
	file_proto_tsscomm_v1_tsscomm_proto_rawDescOnce sync.Once
	file_proto_tsscomm_v1_tsscomm_proto_rawDescData []byte
)

func file_proto_tsscomm_v1_tsscomm_proto_rawDescGZIP() []byte {
	file_proto_tsscomm_v1_tsscomm_proto_rawDescOnce.Do(func() {
		file_proto_tsscomm_v1_tsscomm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_tsscomm_v1_tsscomm_proto_rawDesc), len(file_proto_tsscomm_v1_tsscomm_proto_rawDesc)))
	})
	return file_proto_tsscomm_v1_tsscomm_proto_rawDescData
}

var file_proto_tsscomm_v1_tsscomm_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_tsscomm_v1_tsscomm_proto_goTypes = []any{
	(*PartyId)(nil),           // 0: xlabs.tss.comm.PartyId
	(*TssContent)(nil),        // 1: xlabs.tss.comm.TssContent
	(*SignedMessage)(nil),     // 2: xlabs.tss.comm.SignedMessage
	(*HashEcho)(nil),          // 3: xlabs.tss.comm.HashEcho
	(*Echo)(nil),              // 4: xlabs.tss.comm.Echo
	(*Unicast)(nil),           // 5: xlabs.tss.comm.Unicast
	(*PropagatedMessage)(nil), // 6: xlabs.tss.comm.PropagatedMessage
	(*emptypb.Empty)(nil),     // 7: google.protobuf.Empty
}
var file_proto_tsscomm_v1_tsscomm_proto_depIdxs = []int32{
	1, // 0: xlabs.tss.comm.SignedMessage.tss_content:type_name -> xlabs.tss.comm.TssContent
	3, // 1: xlabs.tss.comm.SignedMessage.hashEcho:type_name -> xlabs.tss.comm.HashEcho
	2, // 2: xlabs.tss.comm.Echo.message:type_name -> xlabs.tss.comm.SignedMessage
	1, // 3: xlabs.tss.comm.Unicast.tss:type_name -> xlabs.tss.comm.TssContent
	5, // 4: xlabs.tss.comm.PropagatedMessage.Unicast:type_name -> xlabs.tss.comm.Unicast
	4, // 5: xlabs.tss.comm.PropagatedMessage.Echo:type_name -> xlabs.tss.comm.Echo
	6, // 6: xlabs.tss.comm.DirectLink.Send:input_type -> xlabs.tss.comm.PropagatedMessage
	7, // 7: xlabs.tss.comm.DirectLink.Send:output_type -> google.protobuf.Empty
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_tsscomm_v1_tsscomm_proto_init() }
func file_proto_tsscomm_v1_tsscomm_proto_init() {
	if File_proto_tsscomm_v1_tsscomm_proto != nil {
		return
	}
	file_proto_tsscomm_v1_tsscomm_proto_msgTypes[2].OneofWrappers = []any{
		(*SignedMessage_TssContent)(nil),
		(*SignedMessage_HashEcho)(nil),
	}
	file_proto_tsscomm_v1_tsscomm_proto_msgTypes[5].OneofWrappers = []any{
		(*Unicast_Tss)(nil),
	}
	file_proto_tsscomm_v1_tsscomm_proto_msgTypes[6].OneofWrappers = []any{
		(*PropagatedMessage_Unicast)(nil),
		(*PropagatedMessage_Echo)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_tsscomm_v1_tsscomm_proto_rawDesc), len(file_proto_tsscomm_v1_tsscomm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_tsscomm_v1_tsscomm_proto_goTypes,
		DependencyIndexes: file_proto_tsscomm_v1_tsscomm_proto_depIdxs,
		MessageInfos:      file_proto_tsscomm_v1_tsscomm_proto_msgTypes,
	}.Build()
	File_proto_tsscomm_v1_tsscomm_proto = out.File
	file_proto_tsscomm_v1_tsscomm_proto_goTypes = nil
	file_proto_tsscomm_v1_tsscomm_proto_depIdxs = nil
}
