// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: protob/frost-signing.proto

package sign

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// round1 message.
type Broadcast2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Di            []byte                 `protobuf:"bytes,1,opt,name=Di,proto3" json:"Di,omitempty"`
	Ei            []byte                 `protobuf:"bytes,2,opt,name=Ei,proto3" json:"Ei,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Broadcast2) Reset() {
	*x = Broadcast2{}
	mi := &file_protob_frost_signing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Broadcast2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Broadcast2) ProtoMessage() {}

func (x *Broadcast2) ProtoReflect() protoreflect.Message {
	mi := &file_protob_frost_signing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Broadcast2.ProtoReflect.Descriptor instead.
func (*Broadcast2) Descriptor() ([]byte, []int) {
	return file_protob_frost_signing_proto_rawDescGZIP(), []int{0}
}

func (x *Broadcast2) GetDi() []byte {
	if x != nil {
		return x.Di
	}
	return nil
}

func (x *Broadcast2) GetEi() []byte {
	if x != nil {
		return x.Ei
	}
	return nil
}

type Broadcast3 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Zi            []byte                 `protobuf:"bytes,1,opt,name=Zi,proto3" json:"Zi,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Broadcast3) Reset() {
	*x = Broadcast3{}
	mi := &file_protob_frost_signing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Broadcast3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Broadcast3) ProtoMessage() {}

func (x *Broadcast3) ProtoReflect() protoreflect.Message {
	mi := &file_protob_frost_signing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Broadcast3.ProtoReflect.Descriptor instead.
func (*Broadcast3) Descriptor() ([]byte, []int) {
	return file_protob_frost_signing_proto_rawDescGZIP(), []int{1}
}

func (x *Broadcast3) GetZi() []byte {
	if x != nil {
		return x.Zi
	}
	return nil
}

var File_protob_frost_signing_proto protoreflect.FileDescriptor

const file_protob_frost_signing_proto_rawDesc = "" +
	"\n" +
	"\x1aprotob/frost-signing.proto\x12\x0ebinance.tsslib\",\n" +
	"\n" +
	"Broadcast2\x12\x0e\n" +
	"\x02Di\x18\x01 \x01(\fR\x02Di\x12\x0e\n" +
	"\x02Ei\x18\x02 \x01(\fR\x02Ei\"\x1c\n" +
	"\n" +
	"Broadcast3\x12\x0e\n" +
	"\x02Zi\x18\x01 \x01(\fR\x02ZiB\fZ\n" +
	"frost/signb\x06proto3"

var (
	file_protob_frost_signing_proto_rawDescOnce sync.Once
	file_protob_frost_signing_proto_rawDescData []byte
)

func file_protob_frost_signing_proto_rawDescGZIP() []byte {
	file_protob_frost_signing_proto_rawDescOnce.Do(func() {
		file_protob_frost_signing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protob_frost_signing_proto_rawDesc), len(file_protob_frost_signing_proto_rawDesc)))
	})
	return file_protob_frost_signing_proto_rawDescData
}

var file_protob_frost_signing_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protob_frost_signing_proto_goTypes = []any{
	(*Broadcast2)(nil), // 0: binance.tsslib.Broadcast2
	(*Broadcast3)(nil), // 1: binance.tsslib.Broadcast3
}
var file_protob_frost_signing_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protob_frost_signing_proto_init() }
func file_protob_frost_signing_proto_init() {
	if File_protob_frost_signing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protob_frost_signing_proto_rawDesc), len(file_protob_frost_signing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protob_frost_signing_proto_goTypes,
		DependencyIndexes: file_protob_frost_signing_proto_depIdxs,
		MessageInfos:      file_protob_frost_signing_proto_msgTypes,
	}.Build()
	File_protob_frost_signing_proto = out.File
	file_protob_frost_signing_proto_goTypes = nil
	file_protob_frost_signing_proto_depIdxs = nil
}
